---
title: "Data Analysis for the Life Sciences - Getting Started"
output: html_notebook
---

Let's blast through the introduction and getting started segment. I imagine it's a good thing to do these anyway since I often forget what I did last time. 

## Getting Help
```{r}
?install.packages
help("install.packages")
```

## Installing packages
````{r}
install.packages("rafalib")
install.packages("downloader")
````

## Importing Data into R
The book mentions using CSV files and whatnot. I spent a good deal of time making a postgres database and we're gonna use that. 
````{r}
#The requisite packages are:
install.packages("RPostgreSQL", "RPostgres")
library(DBI)
library(sqldf)
library(RSQLite)

#The setup for variables for a postgres connection look like:
usr <- "ruser"
psw <- {"RassWord!"}
drv <- RPostgres::Postgres()
hst <- "localhost"
prt <- 5432
dbn <- "project10"	

#Connecting/establishing a connection to the DB looks like
project12 <- dbConnect(drv, dbname = dbn, host = hst, port = prt, user = usr, password = psw)

#issuing a db SQL querry looks like:
numberofrowsQuery <- dbGetQuery(project12, "SELECT COUNT(VAERS_ID) from vaers;")

#some built in commands
dbListTables(project12) 
````